services:
  nordvpn:
    container_name: NordLynx
    image: ghcr.io/bubuntux/nordlynx
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "6881:6881"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY}
      - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
      - NET_LOCAL=10.10.10.0/8,192.168.1.0/24
      - QUERY=filters\[country_id\]=38&filters\[servers_groups\]\[identifier\]=legacy_p2p
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:nordvpn"
    container_name: qbittorrent
    depends_on:
      - nordvpn
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - ${QBIT_CONFIG_FOLDER}:/config
      - ${QBIT_DOWNLOAD_FOLDER}:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped