services:
  nordvpn:
    container_name: NordLynx
    image: ghcr.io/bubuntux/nordlynx
    security_opt:
      - no-new-privileges:true
    cap_add:
      - NET_ADMIN #required
    ports:
      - "8080:8080" # QbitTorrent UI
      - "6881:6881"
      # - "51420:51420" # QbitTorrent
      # - "51420:51420/udp" # QbitTorrent
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1 # Recommended if using ipv4 only
    environment:
      - PRIVATE_KEY=${NORDLYNX_PRIVATE_KEY}
      - ALLOWED_IPS=0.0.0.0/1,128.0.0.0/1
      - NET_LOCAL=10.0.0.0/8,192.168.2.0/24
      - QUERY=filters\[country_id\]=38&filters\[servers_groups\]\[identifier\]=legacy_p2p # 38 is Canada based on country_id in https://api.nordvpn.com/v1/servers/recommendations
      - "POST_UP=ip -4 route add $$(wg | awk -F'[: ]' '/endpoint/ {print $$5}') via $$(ip route | awk '/default/ {print $$3}')"
      - "PRE_DOWN=ip -4 route del $$(route -n | awk '/255.255.255.255/ {print $$1}') via $$(ip route | awk '/default/ {print $$3}')"
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    network_mode: "service:nordvpn"
    container_name: qbittorrent_linuxserver_w_lynx
    depends_on:
      - nordvpn
    environment:
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ${QBIT_CONFIG_FOLDERPATH}:/config
      - ${QBIT_DOWNLOAD_FOLDERPATH}:/downloads
    restart: unless-stopped