version: "3.7"
services:
  nordvpn:
    image: bubuntux/nordvpn:latest
    container_name: nord_wireguard
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TOKEN=${NORDVPN_TOKEN}
      - CONNECT=Switzerland
      - TECHNOLOGY=NordLynx
      - NETWORK=192.186.1.0/24
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent_linuxserver
    network_mode: service:nordvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${QBIT_CONFIG_FOLDERPATH}:/config
      - ${QBIT_DOWNLOAD_FOLDERPATH}:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped